<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ALIPL0482.local" failures="1" tests="3" name="Android" time="26.248" errors="0" timestamp="03 Dec 2020 06:41:10 GMT">
  <testcase classname="com.qa.tests.LoginTests" name="invalidPassword" time="6.893">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service.new] but found [Username and password do not match any user in this service.]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.new] but found [Username and password do not match any user in this service.]
at com.qa.tests.LoginTests.invalidPassword(LoginTests.java:116)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- invalidPassword -->
  <testcase classname="com.qa.tests.LoginTests" name="invalidusername" time="4.504"/>
  <testcase classname="com.qa.tests.LoginTests" name="successLogin" time="4.182"/>
</testsuite> <!-- Android -->
